### PR TITLE
Check if tomb is installed at startup

### PR DESCRIPTION
**Pull request by mgian**
Added a very simple control to check if tomb is installed and in path, if not show a very simple error and exit

### CODE REVIEW

**Comment by mandeep** [comment]
Hi @mgian! Thanks for submitting a pull request to Mausoleum. I'm not sure that I like the idea of showing a message box then closing the GUI application as I'd like the user experience to be as seamless as possible. I think a better practice would be to warn the user that Tomb is not installed when they are installing Mausoleum. What do you think?

**Comment by mgian** [comment]
Hi @mandeep.
I agree that maybe my solution is a little crude, and I will update to include a better and a clearer message.
The check if Tomb is installed before installing Mausoleum is the correct one, but this should be handled by the package manager of the distro, not Mausoleum itself.

However, I think that is a good idea for Mausoleum to check if it can find the Tomb executable at startup, since without it Mausoleum is useless.
Moreover if you don't launch Mausoleum from a shell (but, for example, using the "Run Command" from the KDE menù) , if it cannof find Tomb it does not anything and it does not show any error messages, which are shown if you run Mausoleum from a shell.

Maybe a really nice solution can be to  have a .ini file which contains the path to Tomb (and maybe some other things), with a simple dialog to set them.

**Comment by mandeep** [comment]
Your message and message box are perfectly fine, I would just prefer to have Mausoleum not interact with the user in such a way. What happens if the user has Tomb installed but shutil.which() can't find it? Mausoleum would never open. As far as I know checking for an application to be installed is not guaranteed cross-distro-platform, the only somewhat guaranteed way is to try to use that application. I think the most minimal way would be to add a check in setup.py and print a warning if Mausoleum can't find Tomb. We could also add another warning to self.message in the Mausoelum class of application.py. That way even if a false warning is given, the user could still use Mausoleum. Thoughts?

**Comment by mgian** [comment]
> What happens if the user has Tomb installed but shutil.which() can't find it? Mausoleum would never open 

Which is fine, in my opinion, since it is useless to open Mausoleum if you cannot use it without Tomb, as long as the user is notified of the reason.
shutil.which() just return the path to the executable (according to the documentation) and at runtime is a better way to check if the user can run Tomb.

> As far as I know checking for an application to be installed is not guaranteed cross-distro-platform

True, but my idea is to leave this job to the package manager of the distro (pacman, apt-get, rpm, whatever), which I am sure can do a better job than me.

> I think the most minimal way would be to add a check in setup.py and print a warning if Mausoleum can't find Tomb.

That's ok, but you still have the problem "how to find if Tomb is installed ?" and there is the problem with people who install Tomb in a non-standard location (like, for example, in their home directory).  We should then add an option to pass a custom path to the setup.py and then make Mausoleum aware of the the custom path. I think it is just easier to check that the user have Tomb in its path.

> We could also add another warning to self.message in the Mausoelum class of application.py. That way even if a false warning is given, the user could still use Mausoleum. Thoughts?

It is a nice option, also if I don't get why (and for what) I should be able to run Mausoleum without Tomb installed.
If it is ok for you, I will gladly implement this (and then make another pull request).

**Comment by mandeep** [comment]
> Which is fine, in my opinion, since it is useless to open Mausoleum if you cannot use it without Tomb, as long as the user is notified of the reason.
> shutil.which() just return the path to the executable (according to the documentation) and at runtime is a better way to check if the user can run Tomb.

What I mean is that it is possible for shutil.which() to not find Tomb, even if Tomb is installed in a path that Mausoleum can find. I do not trust path checking as an option, especially if it does not allow Mausoleum to open.

> True, but my idea is to leave this job to the package manager of the distro (pacman, apt-get, rpm, whatever), which I am sure can do a better job than me.

I would love for Mausoleum to be available on many package managers some day. As of right now it is only available on PyPI and can be installed via pip. When a user installs via pip, we can send a warning if Tomb cannot be found. 

> That's ok, but you still have the problem "how to find if Tomb is installed ?" and there is the problem with people who install Tomb in a non-standard location (like, for example, in their home directory). We should then add an option to pass a custom path to the setup.py and then make Mausoleum aware of the the custom path. I think it is just easier to check that the user have Tomb in its path.

This is a job for Mausoleum's configuration page. If a user has installed Tomb into a path not found by Mausoleum, they can specify the path there.

> It is a nice option, also if I don't get why (and for what) I should be able to run Mausoleum without Tomb installed. If it is ok for you, I will gladly implement this (and then make another pull request).

This is less about running Mausoleum when Tomb isn't installed, but more about running Mausoleum when shutil.which() doesn't find the path correctly. Even then, I think showing a message box and then closing Mausoleum is bad practice and reminds me of Windows 98 where everything would throw up an annoying message dialog.

Thoughts?

**Comment by mgian** [comment]
> What I mean is that it is possible for shutil.which() to not find Tomb, even if Tomb is installed in a path that Mausoleum can find. I do not trust path checking as an option, especially if it does not allow Mausoleum to open.

Wait, I used `shutil.which()` (that is the equivalent of the `which` shell command) only to determine if the user can **execute** the program, not if it is installed, thus we are just making sure that the user can **run** Tomb, regardless of where/how it is installed.

> When a user installs via pip, we can send a warning if Tomb cannot be found. 

I am not sure that you can check if an arbitrary binary package is installed from pip since, as far as I understand, pip can just check if other python modules are installed.

> This is less about running Mausoleum when Tomb isn't installed, but more about running Mausoleum when shutil.which() doesn't find the path correctly. 

I agree, but I think It is still important that somehow we notify the user that Mausoleum cannot work since Tomb is missing (or not in the user's path)

Anyway, feel free to close this pull request, I will come up with some better solution

**Comment by mandeep** [comment]
I'm not sure we need to close this pull request because you are right; there needs to be a solution to this problem. My point was that checking for the Tomb path, and then not opening Mausoleum if the path was not found by 'which' is a crude solution that may fail and that would eventually be replaced. I'm in the process of writing a configuration page for Mausoleum, and I've gone ahead and checked in the settings.toml file if you want to take a look at what I have planned for the settings. I really appreciate your discussion and hope you contribute more to the project.

**Comment by mgian** [comment]
I gave a look at the `settings.toml` file and it look promising.

Anyway I am planning to contribute some more code as soon as I will have some more free time to write it ;-)

**Comment by mandeep** [comment]
Hi @mgian, I released version 0.3.0 of Mausoleum that now contains a Config tab that allows the user to select their own tomb path if one is not found. The one thing I forgot to add was a message with a warning that an installation could not be found. This will be fixed in 0.3.1. Let me know if this release addresses your concerns.

**Comment by mandeep** [comment]
Hi @mgian, I hope all is well. I am going to close this PR since Mausoleum now allows the user to change the path of their Tomb installation and warns the user if the default path is not found.

**Pull request closed without merging**
